"""What an expert council run costs (#103): tool calls and the size of what the tools answer, measured here, and the
table in docs/expert-council.md ("Cost of one run") kept equal to what this measures, so no figure in the doc is invented.

What is measured: a Commander deck review ("tune it on a budget"), the flow in skills/expert-council/SKILL.md and each
seated member's own brief (agents/*.md). The calls are counted from those texts; the answers are real MCP answers of this
server (JSON-RPC ``tools/call``, the text a host hands the model) on a fixture catalog: a synthetic 100-card Commander deck
whose card texts are invented and about 150 characters long, prices and roles invented. Tokens are characters divided by 4,
an estimate, not a tokenizer. What is NOT measured and the doc says so: the model's own output, money, the Comprehensive
Rules answers (read live from Wizards, nothing to measure against here), and Commander Spellbook's answer (the twin's).

Update the doc after a change with:  UPDATE_COUNCIL_COST=1 pytest tests/test_council_cost.py
"""

import json
import os
import random
import re
import sys
from datetime import date
from pathlib import Path

import pytest

from tests.test_agents import V1, call_tool, make_token
from tests.test_deck_api import card
from twins import Universe
from vault import catalog_sync as cs
from vault import experts
from vault.app import create_app
from vault.config import Settings

ROOT = Path(__file__).parent.parent
DOC = ROOT / "docs" / "expert-council.md"
BEGIN, END = "<!-- cost:begin generated by tests/test_council_cost.py -->", "<!-- cost:end -->"
sys.path.insert(0, str(ROOT / "scripts"))
import build_plugin as bp  # noqa: E402

# The shared facts the chair gathers once (SKILL.md, "Facts first") and hands to every member.
FACTS = ("deck_stats", "simulate_draws", "deck_legality", "find_combos", "check_decklist", "get_deck_overlap")
LOOKUPS_PER_POINT = 3  # members write at most three points (agents/*.md): at most this many card or rule lookups, an upper bound

# Tool calls each member's own brief tells it to make (fixed ones), counted from agents/<name>.md "How you work", for a
# deck review. `lookups` are the card or rule lookups the member makes per point, at most three points.
MEMBER_CALLS = {
    "vault-commander-expert": {"fixed": ["deck_legality", "deck_stats", "find_combos", "simulate_draws"], "lookups": 0},
    "vault-casual-table": {"fixed": ["deck_stats", "find_combos"], "lookups": LOOKUPS_PER_POINT},
    "vault-judge": {"fixed": ["get_card_oracle", "get_rulings", "search_rules", "get_rule", "verify_citation"], "lookups": 0},
    "vault-devils-advocate": {"fixed": ["validate_deck_changes"], "lookups": LOOKUPS_PER_POINT},
    "vault-synergy-analyst": {"fixed": ["deck_stats", "find_combos", "search_cards", "check_decklist"], "lookups": LOOKUPS_PER_POINT},
    "vault-collection-analyst": {"fixed": ["check_decklist", "get_deck_overlap", "find_upgrades", "shopping_list"], "lookups": 0},
}
RULES_TOOLS = {"search_rules", "get_rule", "verify_citation", "get_rulings"}  # answers not measured here (live Wizards text)

WORDS = ("creature artifact permanent opponent graveyard library battlefield counter target damage mana spell token "
         "attacks blocks enters leaves dies draw discard exile sacrifice destroy return control untap tap").split()


def fixture_text(rng, n):
    return " ".join(rng.choice(WORDS) for _ in range(n)).capitalize() + "."


@pytest.fixture
def world(database_url):
    universe = Universe()
    settings = Settings(database_url=database_url, session_secret="t", dev_login=True, base_url="http://testserver")
    app = create_app(settings, serve_static=False, transport=universe.transport)
    from fastapi.testclient import TestClient
    with TestClient(app) as me, TestClient(app) as bot:
        assert me.post("/api/auth/dev-login").status_code == 200
        rng = random.Random(5)
        cards = [card(1, "Fixture Commander", "Legendary Creature — Elf", ["G"], 4, rank=100, text=fixture_text(rng, 24))]
        cards += [card(2, "Fixture Forest", "Basic Land — Forest", [], 0), card(3, "Fixture Wastes", "Basic Land", [], 0)]
        spells = []  # the last one is not in the deck
        for n in range(4, 66):  # 61 distinct spells in the deck and one more card to add
            spells.append(card(n, f"Fixture Spell {n:02d}", rng.choice(["Creature — Elf", "Artifact", "Instant", "Sorcery", "Enchantment"]),
                               ["G"], float(rng.randint(1, 7)), rank=rng.randint(10, 20000), text=fixture_text(rng, rng.randint(14, 30))))
        cards += spells
        extra = spells.pop()
        cards.remove(extra)
        cards.append(extra)
        roles = {"ramp": spells[:10], "draw": spells[10:20], "removal": spells[20:28], "sweeper": spells[28:30]}
        with app.state.db.sessions() as db:
            cs.sync_oracle_cards(db, cards)
            cs.sync_rulings(db, [{"object": "ruling", "oracle_id": s["oracle_id"], "source": "wotc", "published_at": f"2020-0{i + 1}-01",
                                  "comment": fixture_text(rng, 30)} for s in spells[:12] for i in range(3)])
            cs.sync_oracle_tags(db, [{"id": f"t-{r}", "slug": r, "label": r, "parent_ids": [], "child_ids": [],
                                      "taggings": [{"oracle_id": c["oracle_id"], "weight": "strong"} for c in cs_]}
                                     for r, cs_ in roles.items()])
            cs.sync_oracle_prices(db, [{"oracle_id": c["oracle_id"], "scryfall_id": c["id"], "usd": round(rng.uniform(0.1, 25), 2),
                                        "usd_foil": None, "eur": None, "day": date(2026, 10, 4), "source": "scryfall"} for c in cards])
            for name in ("oracle_cards", "rulings", "oracle_tags", "oracle_prices"):
                cs.record_source(db, name, version=name + "-1", rows=1)
            db.commit()
        lines = ["Commander", "1 Fixture Commander", "", "Deck", "20 Fixture Forest", "17 Fixture Wastes"] + [f"1 {s['name']}" for s in spells]
        text = "\n".join(lines)
        deck = me.post(f"{V1}/decks", json={"name": "Fixture Swarm", "text": text}).json()
        me.post(f"{V1}/decks", json={"name": "Fixture Second", "text": "Commander\n1 Fixture Commander\n\nDeck\n" + "\n".join(f"1 {s['name']}" for s in spells[:30])})
        token = make_token(me)
        yield {"bot": bot, "token": token, "deck": deck, "text": text, "spells": spells, "extra": extra, "me": me}
    app.state.db.engine.dispose()
    assert not universe.escapes, universe.escapes


def measure_answers(w):
    """tool name -> characters of the answer a host hands the model, one measured call each, on the fixture deck."""
    bot, token, deck, text = w["bot"], w["token"], w["deck"], w["text"]
    first = w["spells"][0]
    plan = {"cuts": [w["spells"][-1]["name"]], "adds": [w["extra"]["name"]]}

    def run(tool, **args):
        res = call_tool(bot, token, tool, **args)
        assert not res.get("isError"), (tool, res)
        return len(res["content"][0]["text"])

    out = {
        "list_decks": run("list_decks", query="fixture swarm"),
        "get_deck": run("get_deck", deck_id=deck["id"]),
        "deck_stats": run("deck_stats", deck_id=deck["id"]),
        "simulate_draws": run("simulate_draws", deck_id=deck["id"], format="commander"),
        "deck_legality": run("deck_legality", deck_id=deck["id"], format="commander"),
        "find_combos": run("find_combos", deck_id=deck["id"]),
        "check_decklist": run("check_decklist", text=text),
        "get_deck_overlap": run("get_deck_overlap"),
        "validate_deck_changes": run("validate_deck_changes", deck_id=deck["id"], format="commander", budget_usd=50, **plan),
        "find_upgrades": run("find_upgrades", deck_id=deck["id"], format="commander", budget_usd=10, limit=10),
        "shopping_list": run("shopping_list", deck_id=deck["id"]),
        "search_cards": run("search_cards", query="fixture", limit=10),
        "get_card_oracle": run("get_card_oracle", name=first["name"]),
    }
    return out


def tokens(chars):
    return round(chars / 4)


def cost_table(sizes):
    """The markdown for docs/expert-council.md, computed from the flows and the measured answer sizes."""
    seated = [m["id"] for m in experts.seat("commander", "tune it", budget=True)]
    chair_calls = ["list_decks", "get_deck", *FACTS, "validate_deck_changes"]
    chair_chars = sum(sizes[t] for t in chair_calls)
    facts_chars = sum(sizes[t] for t in FACTS)
    rows, total_calls, total_calls_shared, total_chars, total_chars_shared, total_brief = [], 0, 0, 0, 0, 0
    for member in seated:
        spec = MEMBER_CALLS[member]
        fixed = spec["fixed"]
        shared = [t for t in fixed if t not in FACTS]
        measured_fixed = [t for t in fixed if t not in RULES_TOOLS]
        chars = sum(sizes[t] for t in measured_fixed) + spec["lookups"] * sizes["get_card_oracle"]
        chars_shared = sum(sizes[t] for t in shared if t not in RULES_TOOLS) + spec["lookups"] * sizes["get_card_oracle"]
        n, n_shared = len(fixed) + spec["lookups"], len(shared) + spec["lookups"]
        brief = len(experts.brief(member)["brief"])
        rows.append((member, n, n_shared, chars, chars_shared, brief, any(t in RULES_TOOLS for t in fixed)))
        total_calls += n
        total_calls_shared += n_shared
        total_chars += chars
        total_chars_shared += chars_shared
        total_brief += brief
    chair_brief = len(experts.DATA["chair"]["brief"])
    lines = [
        BEGIN,
        "",
        f"Measured for a Commander deck review (\"tune it on a budget\"): the panel the seating rules pick is "
        f"{', '.join(f'`{m}`' for m in seated)} ({len(seated)} members) and the chair. Tokens are characters divided by 4.",
        "",
        "| Who | Tool calls as its brief says | Tool calls if it reuses the chair's facts | Tool answers read (tokens) as briefed | Tool answers read (tokens) reusing the facts | Brief (tokens) |",
        "|---|---|---|---|---|---|",
        f"| chair (`expert-council`) | {len(chair_calls)} | {len(chair_calls)} | {tokens(chair_chars)} | {tokens(chair_chars)} | {tokens(chair_brief)} |",
    ]
    for member, n, n_shared, chars, chars_shared, brief, rules in rows:
        lines.append(f"| `{member}`{' (+ rules answers, not measured)' if rules else ''} | {n} | {n_shared} | {tokens(chars)} | {tokens(chars_shared)} | {tokens(brief)} |")
    lines.append(f"| **Run** | **{len(chair_calls) + total_calls}** | **{len(chair_calls) + total_calls_shared}** | "
                 f"**{tokens(chair_chars + total_chars)}** | **{tokens(chair_chars + total_chars_shared)}** | **{tokens(chair_brief + total_brief)}** |")
    lines += [
        "",
        "Measured answers (tokens, one call each, on the fixture deck): " + ", ".join(
            f"`{t}` {tokens(sizes[t])}" for t in sorted(sizes)) + f". The chair hands every member the shared facts (`deck_stats` to "
        f"`get_deck_overlap`, together {tokens(facts_chars)} tokens), which each member's context then holds as well: "
        f"{tokens(facts_chars)} tokens in each of the {len(seated)} members' contexts, {tokens(facts_chars) * len(seated)} across the run, "
        "on top of the table. The lists passed as arguments (`check_decklist` takes the whole deck list) are not counted. "
        "Commander Spellbook's answer (`find_combos`) is the twin's, so a real one can be longer.",
        "",
        f"Counting rules: a member's fixed calls are the tools named in its brief's \"How you work\"; members that look at cards "
        f"(casual table, devil's advocate, synergy analyst) make at most {LOOKUPS_PER_POINT} `get_card_oracle` lookups, one per "
        "point (they write at most three points), counted at the measured size of one answer. The judge's rules answers "
        "(`get_rulings`, `search_rules`, `get_rule`, `verify_citation`) are counted as calls but not sized: the rules are read live "
        "from Wizards and no copy exists to measure.",
        "",
        END,
    ]
    return "\n".join(lines)


def test_the_cost_table_in_the_design_doc_is_what_the_flows_and_the_answers_measure(world):
    sizes = measure_answers(world)
    table = cost_table(sizes)
    text = DOC.read_text(encoding="utf-8").replace("\r\n", "\n")
    if os.environ.get("UPDATE_COUNCIL_COST"):
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        DOC.write_text(head + table + tail, encoding="utf-8")
        text = DOC.read_text(encoding="utf-8")
    assert BEGIN in text and END in text, "docs/expert-council.md has no cost section"
    assert table in text, "the doc's cost table is out of date: UPDATE_COUNCIL_COST=1 pytest tests/test_council_cost.py\n" + table


def test_every_call_counted_for_a_member_is_one_its_brief_names_and_its_definition_allows():
    """The counts come from the briefs: each counted tool is one the agent may call and its brief names; a member that is
    counted lookups writes at most three points, so the count is an upper bound; the panel is made of counted members."""
    agents = {a["name"]: a for a in bp.load_agents()}
    for member, spec in MEMBER_CALLS.items():
        body = " ".join(agents[member]["body"].split())
        assert set(spec["fixed"]) <= set(agents[member]["tools"]), member
        assert all(f"`{t}`" in body for t in spec["fixed"]), (member, [t for t in spec["fixed"] if f"`{t}`" not in body])
        assert not spec["lookups"] or "at most three" in body.lower()
        assert not spec["lookups"] or "get_card_oracle" in agents[member]["tools"]
    for goal in ("tune it", "is it legal", "explain the plan"):
        assert {m["id"] for m in experts.seat("commander", goal, budget=True)} <= set(MEMBER_CALLS)
